import Head from 'next/head';

export default function about({data}) {

    const { name } = data;

    return (
        <>
            <Head>
                <title>about</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div style={{
                minHeight: '100vh',
            }}>
                <h1>About</h1>
                <p>{name}</p>
            </div>
        </>
    );
}

export async function getServerSideProps() {
    // Fetch data from external API
    const res = await fetch('http://localhost:3000/api/hello');
    const data = await res.json();

    // Pass data to the page via props
    return { props: { data } };
}